<table>
<?php foreach ($products as $product): ?>
	<tr>
		<td><?= $product['quantity'] ?></td>
		<td><?= $product['name'] ?></td>
		<td><?= Tools::getPrettyPrice(Tools::getPriceTTC($product['priceHT'])) ?></td>
		<td><?= Tools::getPrettyPrice(Tools::getPriceTTC($product['priceHT'] * $product['quantity'])) ?></td>
		<td><button class="btn-delete" data-id="<?= $product['id'] ?>">Supprimer</button></td>
	</tr>

<?php endforeach ?>
</table>